### ISSUE TITLE
Suggestion: Remove naive root uid/euid check

### ISSUE THREAD

**Issue by bcoles** [netdiscover-scanner/netdiscover#14]
`netdiscover` currently performs a `root` check. If the user is not [e]uid `0` the program terminates with an error "You must be root to run this."

https://github.com/netdiscover-scanner/netdiscover/blob/84fbdfeb432fe9c6818ae391461de54f78fdfd0a/src/main.c#L231-L236

Historically this is a reasonable check. However, namespaces and capabilities make a mess of this on Linux.

Low privileged users can gain uid `0` in a user namespace, rendering the check useless:

```
asdf@kali:/root/Desktop/netdiscover$ id
uid=1000(asdf) gid=1000(asdf) groups=1000(asdf)
asdf@kali:/root/Desktop/netdiscover$ unshare -r id
uid=0(root) gid=0(root) groups=0(root)
asdf@kali:/root/Desktop/netdiscover$ unshare -r ./src/netdiscover 
pcap_open_live(): eth0: You don't have permission to capture on that device (socket: Operation not permitted)
```

Users can gain the necessary privileges if the executable is given `cap_net_raw` and `cap_net_admin` capabilities, in which case root privileges are no longer required and the error message is a lie:

```
[2021-11-04 04:54:09] root@kali:~/Desktop/netdiscover# git diff src/main.c
diff --git a/src/main.c b/src/main.c
index 844740b..9aeafcc 100644
--- a/src/main.c
+++ b/src/main.c
@@ -227,14 +227,6 @@ int main(int argc, char **argv)
       exit(1);
    }
 
-
-   /* Check for uid 0 */
-   if ( getuid() && geteuid() )
-   {
-      printf("You must be root to run this.\n");
-      exit(1);
-   }
-
    /* If no iface was specified, autoselect one. exit, if no one available */
    if (datos.interface == NULL)
    {
[2021-11-04 04:54:15] root@kali:~/Desktop/netdiscover# setcap cap_net_raw,cap_net_admin=eip ./src/netdiscover
[2021-11-04 04:54:17] root@kali:~/Desktop/netdiscover# getcap ./src/netdiscover
./src/netdiscover cap_net_admin,cap_net_raw=eip
[2021-11-04 04:54:18] root@kali:~/Desktop/netdiscover# su - asdf
asdf@kali:~$ cd /root/Desktop/netdiscover/
asdf@kali:/root/Desktop/netdiscover$ ./src/netdiscover -P
 _____________________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
 -----------------------------------------------------------------------------
 172.16.191.1    00:50:56:c0:00:08      1      60  VMware, Inc.
^C
asdf@kali:/root/Desktop/netdiscover$ 
```

Rather than performing a [e]uid check or trying to compile with capabilities (`libcap`) to perform a capability check, it is easier to simply call `pcap_open_live()` with the specified interface then let it fail if we don't have the necessary permissions.

In my biased opinion as a competent user, the error message `pcap_open_live(): eth0: You don't have permission to capture on that device (socket: Operation not permitted)` is clear and the error is obvious: I don't have the required permissions.

Where as the error message `You must be root to run this` is of comparatively negligible use and may be a lie.

For reference, this is what `tcpdump` does:

```
asdf@kali:~$ tcpdump 
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)
asdf@kali:~$ tcpdump -i eth0
tcpdump: eth0: You don't have permission to capture on that device
(socket: Operation not permitted)
```

**Comment by jpenalbae** [comment]
I agree with you that Linux capabilities render the uid check obsolete. Anyway you must keep in mind that I wrote this long time ago and the goal was to work on as many other systems besides Linux as possible, such as solaris, several bsd variants, etc... So when making changes we have to be careful not to break portability.

I will remove the uid check (or at least for Linux), but I don't want to rely just on third party library error messages which we do not control. So I will probably add another error message after the one returned by pcap, just to make sure.

Thanks for pointing it out.
