### ISSUE TITLE
autogen.sh: line 4: autoreconf: command not found

### ISSUE THREAD

**Issue by hDmtP** [netdiscover-scanner/netdiscover#18]
I get this error while executing `autogen.sh` in Termux.

Screenshot: 
![Screenshot_2021_1112_105922.jpg](https://user-images.githubusercontent.com/65482473/141414986-af20d4bf-63c8-4493-96a6-51ea37a98280.jpg)

**EDIT**: _resolved the issue by installing `autoconf` and `automake`_.

**Comment by eribertomota** [comment]
Yes, you need to install autoconf.
