### ISSUE TITLE
Error when trying to 'make'.

### ISSUE THREAD

**Issue by robcampbell95** [netdiscover-scanner/netdiscover#2]
oui.h:18:4: note: (near initialization for ‘oui_table[0].vendor’)
make[2]: *** [Makefile:357: misc.o] Error 1
make[2]: Leaving directory '/root/netdiscover-0.3-pre-beta7/src'
make[1]: *** [Makefile:411: all-recursive] Error 1
make[1]: Leaving directory '/root/netdiscover-0.3-pre-beta7'
make: *** [Makefile:330: all] Error 2

Linux 5.2.17-200.fc30.x86_64 #1 SMP Mon Sep 23 13:42:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

**Comment by eribertomota** [comment]
Hi @robcampbell95,

netdiscover-0.3-pre-beta7 is deprecated and out of maintenance. Please, download version 0.5.1.

Regards,

Eriberto
