### ISSUE TITLE
remark: funny side effects

### ISSUE THREAD

**Issue by AWHubGit** [netdiscover-scanner/netdiscover#27]
Running netdiscover simultaneously on two different devices in same LAN has/creates funny side effects. Give it a try!

**Comment by eribertomota** [comment]
Yes, this is not an abnormal reaction. netdiscover uses ARP requests to "excite" the network and this will generate ARP replies. Each ARP reply will be registered by netdiscover. However, the TCP/IP stack in the Kernel could resend an ARP to confirm the MAC/IP if the reply was sent in broadcast. This is the cause of the "funny effects".
