### ISSUE TITLE
Packaging netdiscover for Alpine Linux and update MAC db

### ISSUE THREAD

**Issue by fauust** [netdiscover-scanner/netdiscover#29]
Hi!
I am trying to package netdiscover for alpine https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/52476.

Looks good so far but since it's not possible to download external artifacts during the build (`./update-oui-database.sh`), I am wondering if you could maybe do a new release with an up-to-date MAC database?

Thanks for this excellent tool BTW.
Cheers!

**Comment by eribertomota** [comment]
Hi @fauust,

Yes, it is possible, but... If you release a new package in the future, the same problem will occur. Is not possible to make a patch in Alpine, providing an updated table (file src/oui.h)? I am the netdiscover maintainer on Debian and I use a patch to make the file updated. Please, see here[1].

[1] https://salsa.debian.org/debian/netdiscover/-/blob/debian/master/debian/patches/020_update-oui.patch

Regards,

Eriberto

**Comment by fauust** [comment]
Yeah, that makes sense and seems like a better approach. Since I am not expert with alpine packaging I have asked but that should probably be possible.

**Comment by eribertomota** [comment]
Thanks @fauust . Please, follow this way. I will close this bug. Feel free to reopen.
