### ISSUE TITLE
No devices discovered in Armbian

### ISSUE THREAD

**Issue by cvhessert** [netdiscover-scanner/netdiscover#4]
Hello, I'm using OrangePi with Armbian Bionic, based on Ubuntu 18 and netdiscover is not able to discover devices. Actually it work once for a while, and then suddenly nothing...

I have tried this for long periods with RaspberryPi w Raspbian and was working well.

Any suggestion on what it can be? Thanks

**Comment by eribertomota** [comment]
Hi @cvhessert !

I have a NanoPi using Armbian Debian Bullseye. netdiscover works fine here. What is the command used by you?

**Comment by eribertomota** [comment]
Ping!
