### ISSUE TITLE
update-oui-database.sh has problems on macOS 10.14.x

### ISSUE THREAD

**Issue by willbprog127** [netdiscover-scanner/netdiscover#6]
Greetings!

When I run `update-oui-database.sh` after running `./configure` I get the following error:

```
You need dos2unix command to use this script
```

This is incorrect, as I have dos2unix installed by MacPorts at /opt/local/bin.  This is automatically part of PATH so nothing special is needed.  If I edit the script and completely comment out PATH in the internal variables section, then it properly picks up dos2unix's location.

With the PATH issue worked around, I run the script, and it appears to download properly, but at the end it gives the following error

```
$ ./update-oui-database.sh
Downloading oui.txt from http://standards-oui.ieee.org/oui/oui.txt
Downloader to be used: curl

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4338k  100 4338k    0     0   500k      0  0:00:08  0:00:08 --:--:--  571k

Building the src/oui.h.
sed: illegal option -- z
usage: sed script [-Ealn] [-i extension] [file ...]
       sed [-Ealn] [-i extension] [-e script] ... [-f script_file] ... [file ...]
Done. src/oui.h has        0 MAC addresses.
```

netdiscover works fine on macOS 10.14.x after building, but it doesn't detect manufacturer info because of the above issue.

Thanks! 👍

**Comment by eribertomota** [comment]
Hi @willbprog127,

Pelase, can you verify if attached script works for you?

Regards,

Eriberto

[update-oui-database.sh.zip](https://github.com/netdiscover-scanner/netdiscover/files/4843808/update-oui-database.sh.zip)

**Comment by willbprog127** [comment]
> can you verify if attached script works for you?

Thank you.  It's working good on macOS 10.15.5! 😄 

```
$ ./update-oui-database.sh


Downloading oui.txt from http://standards-oui.ieee.org/oui/oui.txt
Downloader to be used: curl

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4361k  100 4361k    0     0   767k      0  0:00:05  0:00:05 --:--:--  821k


Building the src/oui.h.
Done. src/oui.h has    28155 MAC addresses.
```
