### ISSUE TITLE
i cant download  #7

### ISSUE THREAD

**Issue by misbagas** [netdiscover-scanner/netdiscover#7]
sh-3.2# sh update-oui-database.sh
-n Trying download "oui.txt" with lynx...
-n  with elinks...
 with wget...
update-oui-database.sh: Can't obtain "http://standards-oui.ieee.org/oui.txt"!

**Comment by eribertomota** [comment]
Sounds like your Internet link has a problem. DNS?

What is version of netdiscover?

What is the result of $ wget http://standards-oui.ieee.org/oui/oui.txt  ?

**Comment by misbagas** [comment]
this is the result sir 

eee.org/oui/oui.txt
--2020-06-29 11:55:30--  http://standards-oui.ieee.org/oui/oui.txt
Resolving standards-oui.ieee.org (standards-oui.ieee.org)... 140.98.223.27
Connecting to standards-oui.ieee.org (standards-oui.ieee.org)|140.98.223.27|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4466236 (4.3M) [text/plain]
Saving to: ‘oui.txt’

oui.txt             100%[===================>]   4.26M   241KB/s    in 19s     

2020-06-29 11:55:50 (231 KB/s) - ‘oui.txt’ saved [4466236/4466236]

**Comment by misbagas** [comment]
i cant install you program sir

**Comment by misbagas** [comment]
i was do all step to install you program , but its not working for me

**Comment by eribertomota** [comment]
Hi @misbagas,

When asking for help you need to tell all relevant information, as what is your operational system and post the errors or results of used commands. Otherwise, I’d have to guess. ;-)

**Comment by misbagas** [comment]
sory sir

**Comment by eribertomota** [comment]
It seems to be a joke. Closing.
