### ISSUE TITLE
Install/execution doubts

### ISSUE THREAD

**Issue by misbagas** [netdiscover-scanner/netdiscover#8]
i was do all step for install you prgram 

**This is the result of ./update-oui-database.sh which I have done**

Downloading oui.txt from http://standards-oui.ieee.org/oui/oui.txt
Downloader to be used: curl

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 4361k  100 4361k    0     0   202k      0  0:00:21  0:00:21 --:--:--  239k

Building the src/oui.h.
Done. src/oui.h has    28155 MAC addresses.

**This is the result of ./autogen.sh which I have done**

configure.ac:4: installing 'build-aux/compile'
configure.ac:3: installing 'build-aux/install-sh'
configure.ac:3: installing 'build-aux/missing'
Makefile.am: installing './INSTALL'
src/Makefile.am: installing 'build-aux/depcomp'

**This is the result of ./configure which I have done**

checking for a BSD-compatible install... /usr/local/bin/ginstall -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/local/bin/gmkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables... 
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking whether make supports the include directive... yes (GNU style)
checking dependency style of gcc... gcc3
checking how to run the C preprocessor... gcc -E
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking pcap.h usability... yes
checking pcap.h presence... yes
checking for pcap.h... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating src/Makefile
config.status: creating doc/Makefile
config.status: creating config.h
config.status: executing depfiles commands

Run ./update-oui-database.sh if you want a updated MAC vendors database.

This is the result of (make) which I have done

/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in src
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-main.o -MD -MP -MF .deps/netdiscover-main.Tpo -c -o netdiscover-main.o `test -f 'main.c' || echo './'`main.c
main.c:240:25: warning: 'pcap_lookupdev' is deprecated: use 'pcap_findalldevs'
      and use the first device [-Wdeprecated-declarations]
      datos.interface = pcap_lookupdev(errbuf);
                        ^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pcap/pcap.h:332:1: note: 
      'pcap_lookupdev' has been explicitly marked deprecated here
PCAP_DEPRECATED(pcap_lookupdev, "use 'pcap_findalldevs' and use the firs...
^
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/pcap/funcattrs.h:227:53: note: 
      expanded from macro 'PCAP_DEPRECATED'
  #define PCAP_DEPRECATED(func, msg)    __attribute__((deprecated(msg)))
                                                       ^
1 warning generated.
mv -f .deps/netdiscover-main.Tpo .deps/netdiscover-main.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-ifaces.o -MD -MP -MF .deps/netdiscover-ifaces.Tpo -c -o netdiscover-ifaces.o `test -f 'ifaces.c' || echo './'`ifaces.c
mv -f .deps/netdiscover-ifaces.Tpo .deps/netdiscover-ifaces.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-screen.o -MD -MP -MF .deps/netdiscover-screen.Tpo -c -o netdiscover-screen.o `test -f 'screen.c' || echo './'`screen.c
mv -f .deps/netdiscover-screen.Tpo .deps/netdiscover-screen.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-fhandle.o -MD -MP -MF .deps/netdiscover-fhandle.Tpo -c -o netdiscover-fhandle.o `test -f 'fhandle.c' || echo './'`fhandle.c
mv -f .deps/netdiscover-fhandle.Tpo .deps/netdiscover-fhandle.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-misc.o -MD -MP -MF .deps/netdiscover-misc.Tpo -c -o netdiscover-misc.o `test -f 'misc.c' || echo './'`misc.c
mv -f .deps/netdiscover-misc.Tpo .deps/netdiscover-misc.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-data_reply.o -MD -MP -MF .deps/netdiscover-data_reply.Tpo -c -o netdiscover-data_reply.o `test -f 'data_reply.c' || echo './'`data_reply.c
mv -f .deps/netdiscover-data_reply.Tpo .deps/netdiscover-data_reply.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-data_request.o -MD -MP -MF .deps/netdiscover-data_request.Tpo -c -o netdiscover-data_request.o `test -f 'data_request.c' || echo './'`data_request.c
mv -f .deps/netdiscover-data_request.Tpo .deps/netdiscover-data_request.Po
gcc -DHAVE_CONFIG_H -I. -I..    -fcommon -g -O2 -MT netdiscover-data_unique.o -MD -MP -MF .deps/netdiscover-data_unique.Tpo -c -o netdiscover-data_unique.o `test -f 'data_unique.c' || echo './'`data_unique.c
mv -f .deps/netdiscover-data_unique.Tpo .deps/netdiscover-data_unique.Po
gcc -fcommon -g -O2   -o netdiscover netdiscover-main.o netdiscover-ifaces.o netdiscover-screen.o netdiscover-fhandle.o netdiscover-misc.o netdiscover-data_reply.o netdiscover-data_request.o netdiscover-data_unique.o -lpthread -lpcap 
Making all in doc
make[2]: Nothing to be done for `all'.
make[2]: Nothing to be done for `all-am'.

**This is the result of (make install ) which I have done**

Password:
Making install in src
 /usr/local/bin/gmkdir -p '/usr/local/sbin'
  /usr/local/bin/ginstall -c netdiscover '/usr/local/sbin'
make[2]: Nothing to be done for `install-data-am'.
Making install in doc
make[2]: Nothing to be done for `install-exec-am'.
 /usr/local/bin/gmkdir -p '/usr/local/share/man/man8'
 /usr/local/bin/ginstall -c -m 644 netdiscover.8 '/usr/local/share/man/man8'
make[2]: Nothing to be done for `install-exec-am'.
 /usr/local/bin/gmkdir -p '/usr/local/share/doc/netdiscover'
 /usr/local/bin/ginstall -c -m 644 README COPYING AUTHORS ChangeLog NEWS TODO '/usr/local/share/doc/netdiscover'

but i can still use you program 

zsh: command not found: netdiscover

**this is my screenshot when I do (./update-oui-database.sh)**

<img width="646" alt="step 1" src="https://user-images.githubusercontent.com/56241375/86068360-5d894680-baa1-11ea-8064-901c6ba5a9b0.png">

**this is my screenshot when I do (./autogen.sh)**

<img width="539" alt="step2" src="https://user-images.githubusercontent.com/56241375/86068930-b60d1380-baa2-11ea-9822-7936c6c3a15a.png">

**this is my screenshot when I do (./configure)**

<img width="648" alt="step3" src="https://user-images.githubusercontent.com/56241375/86068944-bf967b80-baa2-11ea-8636-f7f0e7efb33f.png">

**this is my screenshot when I do (make)**

<img width="1280" alt="step4" src="https://user-images.githubusercontent.com/56241375/86068952-c624f300-baa2-11ea-8c39-6c6bba3d0a5c.png">

**this is my screenshot when I do (make install)**

<img width="885" alt="step5" src="https://user-images.githubusercontent.com/56241375/86068962-ccb36a80-baa2-11ea-854d-8a6eca7fc597.png">

why i cant still use you program , but i have done all job for use you program 

this is my eror 

zsh: command not found: netdiscover

**Comment by eribertomota** [comment]
The program is being installed in  '/usr/local/sbin' and must be run as root user.

**Comment by misbagas** [comment]
Sir while I try typing (make install) why an error

this is the eror

Making install in src
 /usr/local/bin/gmkdir -p '/usr/local/sbin'
  /usr/local/bin/ginstall -c netdiscover '/usr/local/sbin'
ginstall: cannot overwrite directory '/usr/local/sbin/netdiscover' with non-directory
make[2]: *** [install-sbinPROGRAMS] Error 1
make[1]: *** [install-am] Error 2
make: *** [install-recursive] Error 1

i was download in /usr/local/sbin

**Comment by eribertomota** [comment]
Please, post the result of 'ls -l /usr/local/sbin'

**Comment by misbagas** [comment]
this is my scrennshoot of ls -l /usr/local/sbin 
<img width="1046" alt="sbin" src="https://user-images.githubusercontent.com/56241375/86071166-c922e200-baa8-11ea-8441-da0295c24b0e.png">

**Comment by eribertomota** [comment]
> i was download in /usr/local/sbin
> and i was login as root i use macos

The install process needs install the file netdiscover in /usr/local/sbin. However, you downloaded the source code in /usr/local/sbin and you created the netdiscover directory. Considering that /usr/local/sbin/netdiscover is a current directory, the executable file /usr/local/sbin/netdiscover can't be created.

**Comment by misbagas** [comment]
so, suppose I installed netdiscover on my desktop, then another folder in / usr / local / sbin

**Comment by eribertomota** [comment]
HI @misbagas,

Can I close this issue?
