### ISSUE TITLE
netdiscover doesn't work with newer version of libpcap

### ISSUE THREAD

**Issue by fajard01** [netdiscover-scanner/netdiscover#9]
I'm on archlinux and I can confirm netdiscover doesn't function properly with the latest libpcap version 1.10. It always outputs success but the lists of ip addresses is empty. In Kali virtual machine, netdiscover only functions if libpcap0 is in version 1.08.

Steps to reproduce: install libpcap > 1.08
Install netdiscover

Expected output: list of scanned network

**Comment by eribertomota** [comment]
Hi @fajard01,

I am in Debian Testing with libpcap 1.10.0 and netdiscover works fine. What is the command used by you? Only '# netdiscover'? Can you try in a fresh install of Arch Linux?

Eriberto

**Comment by ArtemProc** [comment]
@eribertomota I
have tested on Kali with libpcap0.8/kali-rolling,now 1.10.0-2 amd64

SETUP:
VMWare WS PRO
4 VMs on NAT Network  -> same NW

Command:
sudo netdiscover -P -r 192.168.163.0/24

Gave no results
I have even tried to compile from sources same result - nothing.

Only if I downgrade to libpcap0.8_1.8.1-6_amd64.deb - I able to see results - with SAME NW configuration

**Comment by eribertomota** [comment]
Humm... Now in Debian Testing, using libpcap 1.10.0-2. Netdiscover works fine for me. See below:

```
root@canopus:~# netdiscover -P -r 172.16.0.0/16
 _____________________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
 -----------------------------------------------------------------------------
 172.16.0.72     c4:57:6e:b1:d0:a6      1      60  Samsung Electronics Co.,Ltd
 172.16.0.40      18:0d:2c:c2:e6:07      1      60  Intelbras
 172.16.0.10    38:2c:4a:c7:a3:e4      1      60  ASUSTek COMPUTER INC.
```
 
Considering a host 192.168.163.1 inside your network, what is the result of the following command, when running `netdiscover -P -r 172.16.0.0/16`?

`# tcpdump -n arp host 192.168.163.1`

**Comment by jpenalbae** [comment]
My guess is that it might be due to vmware. I have seen similar problems before when using VMs due to the networking setup.

Just run tcpdump on all the systems as @eribertomota suggests, and see if the replies and responses are being properly forwarded by your network setup.

**Comment by eribertomota** [comment]
> Humm... Now in Debian Testing, using libpcap 1.10.0-2. Netdiscover works fine for me. See below:
> 
> ```
> root@canopus:~# netdiscover -P -r 172.16.0.0/16
>  _____________________________________________________________________________
>    IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
>  -----------------------------------------------------------------------------
>  172.16.0.72     c4:57:6e:b1:d0:a6      1      60  Samsung Electronics Co.,Ltd
>  172.16.0.40      18:0d:2c:c2:e6:07      1      60  Intelbras
>  172.16.0.10    38:2c:4a:c7:a3:e4      1      60  ASUSTek COMPUTER INC.
> ```
> 
> Considering a host 192.168.163.1 inside your network, what is the result of the following command, when running `netdiscover -P -r 192.168.163.1`?
> 
> `# tcpdump -n arp host 192.168.163.1`

I edited my last message because the IP address in netdiscover command used as an example was wrong.

I also think that the problem is the VMWare.

Thanks!

**Comment by ArtemProc** [comment]
Hi @eribertomota @jpenalbae .
1. thank you for reply.
2. Here is results on screenshots - I have 192.168.163.143 server UP
![image](https://user-images.githubusercontent.com/10011238/111919154-c8900880-8a88-11eb-872d-ad7a6a712f72.png)

**Comment by eribertomota** [comment]
What is the result for `# tcpdump -D`?

**Comment by ArtemProc** [comment]
`┌──(root💀kali-study-vm)-[/home/kali]
└─# tcpdump -D
1.eth0 [Up, Running, Connected]
2.any (Pseudo-device that captures on all interfaces) [Up, Running]
3.lo [Up, Running, Loopback]
4.bluetooth-monitor (Bluetooth Linux Monitor) [Wireless]
5.nflog (Linux netfilter log (NFLOG) interface) [none]
6.nfqueue (Linux netfilter queue (NFQUEUE) interface) [none]
7.dbus-system (D-Bus system bus) [none]
8.dbus-session (D-Bus session bus) [none]
`

**Comment by eribertomota** [comment]
Can you try `# netdiscover -P -r 192.168.163.0/24 -i eth0` and  `# netdiscover -P -i eth0`?

**Comment by ArtemProc** [comment]
Look like it **work if there is no -r supplied.**

But obviously it is scanning a lot more than required and time consumption is higher.

```
──(root💀kali-study-vm)-[/home/kali]
└─# netdiscover -P -r 192.168.163.0/24 -i eth0
 _____________________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
 -----------------------------------------------------------------------------

-- Active scan completed, 0 Hosts found.
                                                                                      
┌──(root💀kali-study-vm)-[/home/kali]
└─# netdiscover -P -i eth0
 _____________________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
 -----------------------------------------------------------------------------
 192.168.163.1   00:50:56:c0:00:08      1      60  VMware, Inc.
 192.168.163.2   00:50:56:eb:68:10      1      60  VMware, Inc.
 192.168.163.143 00:0c:29:9e:f9:06      1      60  VMware, Inc.
 192.168.163.254 00:50:56:e1:58:bf      1      60  VMware, Inc.

```

**Comment by eribertomota** [comment]
Please, try `# netdiscover -P -r 192.168.0.0/16`

**Comment by eribertomota** [comment]
@jpenalbae in my network, using a real machine, the following command works fine:

`root@canopus:~# netdiscover -P -i eth0 -r 172.16.0.0/16`

However, with /24, returns nothing.

`root@canopus:~# netdiscover -P -i eth0 -r 172.16.0.0/24`

I have hosts using 172.16.0.x.

**Comment by eribertomota** [comment]
@jpenalbae Using /8 works fine too.

**Comment by ArtemProc** [comment]
@eribertomota with wider mask work as well for me, so /24 some how party breaker
```

──(root💀kali-study-vm)-[/home/kali]
└─# netdiscover -P -r 192.168.0.0/16                                            130 ⨯
 _____________________________________________________________________________
   IP            At MAC Address     Count     Len  MAC Vendor / Hostname      
 -----------------------------------------------------------------------------
 192.168.163.1   00:50:56:c0:00:08      1      60  VMware, Inc.
 192.168.163.2   00:50:56:eb:68:10      1      60  VMware, Inc.
 192.168.163.143 00:0c:29:9e:f9:06      1      60  VMware, Inc.
 192.168.163.254 00:50:56:e1:58:bf      1      60  VMware, Inc.

```

**Comment by eribertomota** [comment]
> @eribertomota with wider mask work as well for me, so /24 some how party breaker

Sure.

**Comment by ArtemProc** [comment]
thank you for your quick reply and your work on tool.
I can say with /16 as it works - for my purpose it is totally fine.

but as it used to work fine with /24 before, please consider this as feedback).

I appreciate your time to reply in to me.

Thank you.

**Comment by fajard01** [comment]
The /16 mask works for me as well and I'm using Kali in Virtualbox.
But as everyone else /24 is not functioning.

**Comment by tintinnya** [comment]
Are you running netdiscover on Linux under VMware Fusion or Oracle VirtualBox? There's a chance that the result is not as expected. I'm running netdiscover on Kali Linux nder VMware Fusion and Oralce VirtualBox. None of them are giving me the expected result. 

![](https://tintinnya.com/wp-content/uploads/2021/04/netdiscover-not-working-1024x506.png)

Then I downgraded the libpcap0.8 to the stable version and it works

![](https://tintinnya.com/wp-content/uploads/2021/04/netdiscover-works.png)

The strange part is, Kali Linux on AWS with the latest netdiscover 0.7.3 and latest libpcap0.8 1.10.0-2 is showing the expected result. 

![](https://tintinnya.com/wp-content/uploads/2021/04/kali-on-cloud-runs-netdiscover-properly.png)

Perhaps something blocks the libpcap0.8 to run properly in VMware Fusion 10.5 and Oracle VirtualBox 6.1.8. Not sure with that. Hey, I put the details on [my blog](https://tintinnya.com/2021/04/netdiscover-on-kali-2020-3-could-not-see-any-mac-addresses/).

**Comment by fajard01** [comment]
@tintinnya 
As stated from the posts above, the new version works as long as the /16 masak is used but doesn't work if you use the /24 mask. As you posted, AWS works because you use the /16 mask there as opposed to your VM versions where you used the /24 mask.

**Comment by tintinnya** [comment]
Hi @fajard01 , thank you for pointing this out. I didn't realized the CIDR I used between those environment. You are correct, when using /24, netdiscover not giving me the expected result as /16.

![](https://tintinnya.com/wp-content/uploads/2021/04/libpcap-latest.png)

But when I downgraded the libpcap0.8 to 1.8.1-6, both /24 and /16 gave me the expected result.

![](https://tintinnya.com/wp-content/uploads/2021/04/libpcap-stable.png)

I'll let @eribertomota decide whether this is libpcap0.8 or netdiscover 0.7

**Comment by JohnnyBeGood70** [comment]
I can confirm the /24 problem exists in latest linux mint with default package installations too:

netdiscover : 0.5.1-4
libpcap0.8 : 1.9.1-3

I tried to compile the latest netdiscover from source, but it doesn't help.

**Comment by tintinnya** [comment]
just curious, what is your output of ifconfig @JohnnyBeGood70 ?

I realized that on my vmware, my network mask is 0xffffff00 hence my network is on /24, but on AWS I'm using netmask 0xfffff000 hence my network is on /20. But due to restriction on netdiscover that CIDR notation only allow /24, /16, and /8, then I have to use /16 instead of /20. 

In AWS, my Kali linux network is
```
eth0: flags=4163<UP, BROADCAST, RUNNING, MULTICAST> mtu 9001
         172.31.3.32  netmask 255.255.240.0  broadcast 172.31.15.255
```
![image](https://user-images.githubusercontent.com/24727287/114968762-33bed600-9ea1-11eb-8063-72c0f790c711.png)

of course I can't find anything with netdiscover -i eth0 -r 172.31.3.0/24 -P because my target is on 172.31.12.242, hence using /16 is able to discover the target.

The question will be raised if your network is /24 but your netdiscover command is /16. ARP packages will be sent by your Kali and captured by the computer to know who is on the same local network. I don't know whether ARP package can be broadcasted outside local network and will be replied by servers outside the gateway computer.

but it still not explaining why netdiscover with /24 with latest libpcap0.8 is not working, but using the old stable libpcap0.8 and /24 is working.

**Comment by JohnnyBeGood70** [comment]
@tintinnya Hi, my network interface, where I want to run netdiscover from, is up, but not configured to any network so ifconfig doesn't tell any IP config here. Configuring to a network is, I guess, not neccesary, since ARP happens one layer below that. I just want to use (test) netdiscover to find out the unknown static IP address of a device connected directly to the eth port in question. If I'm scanning the /16 networks the device gets found (once I'm scanning its proper subnet), but not with /24.

**Comment by RDXV** [comment]
Hi, even I am facing the same problem in Kali Virutal box where 'netdiscover -r 10.0.2.1/24' just says scan finished and does not giver any output as  of 27 May 2021. Although, the 'netdiscover -r 10.0.2.1//16' gives output, the /24 does not show anything. I reinstalled kali and still same problem. Any way by which I can solve it like downgrading libcap?

**Comment by fajard01** [comment]
https://packages.debian.org/buster/amd64/libpcap0.8/download

**Comment by RDXV** [comment]
thanks

**Comment by ensch** [comment]
Increasing the `to_ms` parameter in the call to `pcap_open_live` in `src/ifaces.c` from 0 to 512 fixes the problem for me with newer versions of libpcap (tested with 1.10.0). 

```c
descr = pcap_open_live(datos->interface, BUFSIZ, 1, PCAP_TOUT, errbuf);
```

```patch
diff --git a/src/ifaces.h b/src/ifaces.h
index 68ce8a5..3fbdaf4 100644
--- a/src/ifaces.h
+++ b/src/ifaces.h
@@ -45,7 +45,7 @@ extern "C"
       typedef uint16_t u_int16_t;
       typedef uint8_t  u_int8_t;
    #else
-      #define PCAP_TOUT 0
+      #define PCAP_TOUT 512
    #endif
```

**Comment by eribertomota** [comment]
After several tests in Debian Sid, I confirm that last patch, sent by @ensch, works fine.

**Comment by Mama0africa** [comment]
Hello, i have same issue (netdiscover -P -r 192.168.163.0/24 -i eth0) this command works totally fine, but what if i want to detect using wlan0? (Noting works)
